apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: keycloak
spec:
  maxReplicas: 20
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 60
    type: Resource
  - resource:
      name: cpu
      targetAverageUtilization: 40
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: keycloak
