apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: keycloak
  namespace: keycloak
spec:
  maxReplicas: 20
  metrics:
  - resource:
      name: memory
      targetAverageUtilization: 70
    type: Resource
  - resource:
      name: cpu
      targetAverageUtilization: 70
    type: Resource
  minReplicas: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: keycloak
